---
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.64.1/hugo_0.64.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.64.1_Linux-64bit.deb

script:
  - hugo

deploy:
  - provider: script
    skip_cleanup: true
    script: "bash ./deploy.sh"
    on:
      branch: master
