---
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.129.0/hugo_extended_0.129.0_linux-amd64.deb
  - sudo dpkg -i hugo_extended_0.129.0_linux-amd64.deb

script:
  - hugo --gc --minify --baseURL https://ishabbi.tech

deploy:
  - provider: script
    skip_cleanup: true
    script: "bash ./deploy.sh"
    on:
      branch: master
